"""Fix withdrawn enum

Revision ID: 838fe3213d70
Revises: eccf5da1e39b
Create Date: 2025-06-28 03:55:05.412685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '838fe3213d70'
down_revision = 'eccf5da1e39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('complaint_status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'resolved', 'closed', 'withdrawn', name='complaint_status_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('complaint_status',
               existing_type=postgresql.ENUM('open', 'in_progress', 'resolved', 'closed', 'withdrawn', name='complaint_status_enum'),
               nullable=True)

    # ### end Alembic commands ###
