services:
  - type: web
    name: emotion-support-docs
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
    rootDir: Documentation Page with Backend
